version: '3.7'

services:
    app:
        build: ./app
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
          - ./app/:/usr/src/app/
        environment:
            - FLASK_ENV=development
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
            - FLASK_RUN_CERT=cert.pem
            - FLASK_RUN_KEY=key.pem
    react_frontend:
        build: ./react_frontend
        stdin_open: true
        expose:
            - 3000
        ports:
            - '80:3000'
        links:
          - app